services:
  app:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/lang-portal-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: Prod
      PORT: 8080
      BLUEPRINT_DB_URL: ./words.db
      REGISTRY: ghcr.io
      OWNER: $${GITHUB_REPOSITORY_OWNER,,}
    volumes:
      - sqlite_bp:/app/db
      - ./words.db:/app/words.db
  frontend:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/lang-portal-frontend:${TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      REGISTRY: ghcr.io
      OWNER: $${GITHUB_REPOSITORY_OWNER,,}
    depends_on:
      - app
volumes:
  sqlite_bp:
