version: '3.8'

services:
  speach-app:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/speach-app:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - REGISTRY=ghcr.io
      - OWNER=$${GITHUB_REPOSITORY_OWNER,,}
    # These are optional settings you might want to consider:
    restart: unless-stopped
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - .venv/
    #     - action: rebuild
    #       path: ./pyproject.toml