services:
  # Streamlit service (renamed from voacab_importer)
  quiz-gen:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/vocab-importer-ui:${TAG:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.streamlit
    ports:
      - "${VOCAB_IMPORT_UI_PORT:-8504}:8503"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - SERVICE_TYPE=streamlit
      - REGISTRY=ghcr.io
      - OWNER=$${GITHUB_REPOSITORY_OWNER,,}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  # FastAPI service
  quiz-gen:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/vocab-importer-api:${TAG:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.fastapi
    ports:
      - "${VOCAB_IMPORT_API_PORT:-8004}:8004"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - SERVICE_TYPE=fastapi
      - REGISTRY=ghcr.io
      - OWNER=$${GITHUB_REPOSITORY_OWNER,,}
    # These are optional settings you might want to consider:
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml