[project]
name = "asl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autocorrect==2.6.1",
    "imageio==2.31.1",
    "mediapipe",
    "opencv-python==4.8.0.74",
    "scikit-learn==1.2.0",
    "tensorflow",
]
