services:
  # Streamlit service (renamed from voacab_importer)
  streamlit_app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - SERVICE_TYPE=streamlit
    # These are optional settings you might want to consider:
    restart: unless-stopped
    # For development, uncomment the 'develop' section below:
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  # FastAPI service
  fastapi_app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - SERVICE_TYPE=fastapi
    # These are optional settings you might want to consider:
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml