services:
  voacab_importer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
    # These are optional settings you might want to consider:
    restart: unless-stopped
    # For development, uncomment the 'develop' section below:
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - .venv/
    #     - action: rebuild
    #       path: ./pyproject.toml