services:
  # FastAPI service
  writing_practice_api:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/writing-practice-api:${TAG:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.fastapi
    ports:
      - "${WRITING_PRACTICE_API_PORT:-8001}:8001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - UV_LINK_MODE=copy
      - SERVICE_TYPE=fastapi
      - REGISTRY=ghcr.io
      - OWNER=$${GITHUB_REPOSITORY_OWNER,,}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml