services:
  writing-practice:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/listening-comp:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - REGISTRY=ghcr.io
      - OWNER=$${GITHUB_REPOSITORY_OWNER,,}
    # These are optional settings you might want to consider:
    restart: unless-stopped
    # For development, uncomment the 'develop' section below:
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - .venv/
    #     - action: rebuild
    #       path: ./pyproject.toml