#!/usr/bin/env bash
# Populate .env files from ~/.secrets/sorami/.env or fall back to .env.example
# Usage: scripts/init-env.sh [REPO_ROOT]
set -euo pipefail

ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
SECRETS_DIR="${SORAMI_SECRETS_DIR:-$HOME/.secrets/sorami}"
SECRETS_FILE="$SECRETS_DIR/.env"

find_free_port() {
    local base=$1
    local port=$base
    while lsof -i:"$port" >/dev/null 2>&1; do
        port=$((port + 1))
    done
    echo "$port"
}

if [ -f "$SECRETS_FILE" ]; then
    echo "Found secrets at $SECRETS_FILE"
    set -a
    source "$SECRETS_FILE"
    set +a

    DB_USER_VALUE="${DB_USER:-${POSTGRES_USER:-sorami_user}}"
    DB_PASSWORD_VALUE="${DB_PASSWORD:-${POSTGRES_PASSWORD:-}}"
    DB_NAME_VALUE="${DB_NAME:-${POSTGRES_DB:-sorami}}"
    POSTGRES_USER_VALUE="${POSTGRES_USER:-$DB_USER_VALUE}"
    POSTGRES_PASSWORD_VALUE="${POSTGRES_PASSWORD:-$DB_PASSWORD_VALUE}"
    POSTGRES_DB_VALUE="${POSTGRES_DB:-$DB_NAME_VALUE}"
    SEED_BUNDLE_VALUE="${SEED_BUNDLE_PATH:-}"
    if [ -z "$SEED_BUNDLE_VALUE" ]; then
        if [ -d "$ROOT/lang-portal/data/cleaned_json/db" ]; then
            SEED_BUNDLE_VALUE="$ROOT/lang-portal/data/cleaned_json/db"
        elif [ -d "$HOME/github/free-genai-bootcamp-2025/lang-portal/data/cleaned_json/db" ]; then
            SEED_BUNDLE_VALUE="$HOME/github/free-genai-bootcamp-2025/lang-portal/data/cleaned_json/db"
        fi
    fi

    BACKEND_PORT=$(find_free_port "${PORT:-8080}")
    FRONTEND_PORT=$(find_free_port "${FRONTEND_PORT:-3000}")
    DB_PORT=$(find_free_port "${DB_PORT:-5432}")

    echo "Ports: backend=$BACKEND_PORT frontend=$FRONTEND_PORT db=$DB_PORT"

    mkdir -p "$ROOT/lang-portal"
    cat > "$ROOT/lang-portal/.env" << EOF
# Generated by 'just init' from $SECRETS_FILE
APP_ENV=${APP_ENV:-local}
PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT

DB_HOST=${DB_HOST:-localhost}
DB_PORT=$DB_PORT
DB_USER=$DB_USER_VALUE
DB_PASSWORD=$DB_PASSWORD_VALUE
DB_NAME=$DB_NAME_VALUE
POSTGRES_USER=$POSTGRES_USER_VALUE
POSTGRES_PASSWORD=$POSTGRES_PASSWORD_VALUE
POSTGRES_DB=$POSTGRES_DB_VALUE

CLERK_ISSUER=${CLERK_ISSUER:-}
CLERK_JWKS_URL=${CLERK_JWKS_URL:-}
CLERK_AUDIENCE=${CLERK_AUDIENCE:-}
CLERK_SECRET_KEY=${CLERK_SECRET_KEY:-}

ALLOW_DEV_FALLBACK_USER=${ALLOW_DEV_FALLBACK_USER:-0}
SEED_BUNDLE_PATH=${SEED_BUNDLE_VALUE:-}
BLUEPRINT_DB_URL=${BLUEPRINT_DB_URL:-./words.db}
EOF
    echo "Generated lang-portal/.env"

    mkdir -p "$ROOT/lang-portal/frontend"
    cat > "$ROOT/lang-portal/frontend/.env" << EOF
# Generated by 'just init' from $SECRETS_FILE
NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL:-/sign-in}
NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL:-/sign-up}
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL:-/dashboard}
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL:-/dashboard}
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}
CLERK_SECRET_KEY=${CLERK_SECRET_KEY:-}
PORT=$FRONTEND_PORT
GO_BACKEND_URL=http://localhost:$BACKEND_PORT
NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV:-development}
NEXT_PUBLIC_VAPI_PUBLIC_KEY=${NEXT_PUBLIC_VAPI_PUBLIC_KEY:-}
NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY:-}
NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST:-https://eu.i.posthog.com}

SENTRY_ORG=${SENTRY_ORG:-sorami}
SENTRY_PROJECT=${SENTRY_PROJECT:-lang-portal-frontend}
SENTRY_DSN=${SENTRY_DSN:-}
EOF
    echo "Generated lang-portal/frontend/.env"

    mkdir -p "$ROOT/agent"
    cat > "$ROOT/agent/.env" << EOF
# Generated by 'just init' from $SECRETS_FILE
TAVILY_API_KEY=${TAVILY_API_KEY:-}
YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
GMAIL_USER=${GMAIL_USER:-}
GMAIL_PASS=${GMAIL_PASS:-}
GROQ_API_KEY=${GROQ_API_KEY:-}
EOF
    echo "Generated agent/.env"

    mkdir -p "$ROOT/writing-practice"
    cat > "$ROOT/writing-practice/.env" << EOF
# Generated by 'just init' from $SECRETS_FILE
API_HOST=${API_HOST:-localhost}
API_PORT=${API_PORT:-5000}
API_PROTOCOL=${API_PROTOCOL:-http}
GRADIO_SERVER_PORT=${GRADIO_SERVER_PORT:-8081}
GRADIO_SERVER_NAME=${GRADIO_SERVER_NAME:-0.0.0.0}
GROQ_API_KEY=${GROQ_API_KEY:-}
GROUP_ID=${GROUP_ID:-1}
EOF
    echo "Generated writing-practice/.env"

    mkdir -p "$ROOT/vocab-importer"
    cat > "$ROOT/vocab-importer/.env" << EOF
# Generated by 'just init' from $SECRETS_FILE
TAVILY_API_KEY=${TAVILY_API_KEY:-}
YOUTUBE_API_KEY=${YOUTUBE_API_KEY:-}
GMAIL_USER=${GMAIL_USER:-}
GMAIL_PASS=${GMAIL_PASS:-}
GROQ_API_KEY=${GROQ_API_KEY:-}
VOCAB_IMPORT_UI_PORT=${VOCAB_IMPORT_UI_PORT:-8501}
VOCAB_IMPORT_API_PORT=${VOCAB_IMPORT_API_PORT:-8000}
EOF
    echo "Generated vocab-importer/.env"

    echo ""
    echo "All .env files generated. Backend port: $BACKEND_PORT, Frontend port: $FRONTEND_PORT"
else
    echo "No secrets file at $SECRETS_FILE"
    echo "Falling back to .env.example files..."
    [ ! -f "$ROOT/lang-portal/.env" ] && cp "$ROOT/lang-portal/.env.example" "$ROOT/lang-portal/.env" && echo "Created lang-portal/.env"
    [ ! -f "$ROOT/lang-portal/frontend/.env" ] && cp "$ROOT/lang-portal/frontend/.env.example" "$ROOT/lang-portal/frontend/.env" && echo "Created lang-portal/frontend/.env"
    [ ! -f "$ROOT/agent/.env" ] && cp "$ROOT/agent/.env.example" "$ROOT/agent/.env" && echo "Created agent/.env"
    [ ! -f "$ROOT/writing-practice/.env" ] && cp "$ROOT/writing-practice/.env.example" "$ROOT/writing-practice/.env" && echo "Created writing-practice/.env"
    [ ! -f "$ROOT/vocab-importer/.env" ] && cp "$ROOT/vocab-importer/.env.example" "$ROOT/vocab-importer/.env" && echo "Created vocab-importer/.env"
    echo ""
    echo "Run 'just secrets-template' to create a master secrets template, then copy to $SECRETS_FILE"
fi
