services:
  # Streamlit service (renamed from voacab_importer)
  shopping_agent_ui:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/shopping-agent-ui:${TAG:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.streamlit
    ports:
      - "${VOCAB_IMPORT_UI_PORT:-8503}:8503"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - SERVICE_TYPE=streamlit
      - REGISTRY=ghcr.io
      - OWNER=$${GITHUB_REPOSITORY_OWNER,,}  # Force lowercase conversion
    # These are optional settings you might want to consider:
    restart: unless-stopped
    # For development, uncomment the 'develop' section below:
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  # FastAPI service
  shopping_agent_api:
    image: ${REGISTRY:-ghcr.io}/${OWNER:-$GITHUB_REPOSITORY_OWNER}/shopping-agent-api:${TAG:-latest}
    build:
      context: .
      dockerfile: .docker/Dockerfile.fastapi
    ports:
      - "${VOCAB_IMPORT_API_PORT:-8002}:8002"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Add any environment variables your app needs here
      - UV_LINK_MODE=copy
      - SERVICE_TYPE=fastapi
      - REGISTRY=ghcr.io
      - OWNER=$${GITHUB_REPOSITORY_OWNER,,}  # Force lowercase conversion
    # These are optional settings you might want to consider:
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml