name: Build and Push Listening Comp Service

on:
  push:
    branches: [main]
    paths:
      - 'listening-comp/**'
  pull_request:
    branches: [main]
    paths:
      - 'listening-comp/**'

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  PORT: 8080
  APP_ENV: production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push listening-comp services
        run: |
          cd listening-comp
          if [ -f .env.example ]; then
            touch .env
          fi
          docker compose build
          docker compose push
          docker system prune -af